cuda_visible_devices: 0

data_path: ../data/ml-1m.txt

dataset:
  max_length: 50
  # num_negatives:
  full_negative_sampling: False

dataloader:
  batch_size: 2048
  test_batch_size: 512
  num_workers: 256
  validation_size: 10000

model: MAMBA4Rec
model_params:
  input_size: 64
  hidden_size: 64
  num_layers: 1
  dropout: 0.1
  maxlen: 200        
  hidden_units: 64     
  num_blocks: 2            
  dropout_rate: 0.1    
  initializer_range: 0.02  
  mamba_config: # Parameters specific to the Mamba layer itself
    d_model: 32
    d_state: 8
    d_conv: 2
    expand: 2

seqrec_module:
  lr: 0.0001
  predict_top_k: 10
  filter_seen: True

trainer_params:
  max_epochs: 100

patience: 10
sampled_metrics: False
top_k_metrics: [10, 100]
